name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Artifact from action"> artifact.txt
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt

